### ISSUE TITLE
Add the last episode to the feed when subscribing to a new series

### ISSUE THREAD

**Issue by manuelstofer** [yomypopcorn/yo-service#11]
Would make the feed look less empty in the beginning

**Comment by MathisB** [comment]
Yeah an example would make a lot of sense

**Comment by maxkueng** [comment]
This can be tricky from a usability perspective. Let's say I subscribe to a show and then immediately decide that I don't want to subscribe it after all - or maybe I was just playing with the buttons. If the latest episode would be automatically added to the feed when subscribing then I would have shows in my feed even though I don't actually want them.

**Comment by manuelstofer** [comment]
@maxkueng We could remove all entries of a show from the feed when unsubscribing.

**Comment by maxkueng** [comment]
I fixed it. Now when you subscribe to a show the latest episode will be added to your feed. If you unsubscribe all feed items from that show will be removed.

**Comment by manuelstofer** [comment]
cool!

**Comment by MathisB** [comment]
awesome!
