### ISSUE TITLE
"Add more shows" button gets hidden when a lot of shows are added

### ISSUE THREAD

**Issue by MathisB** [yomypopcorn/yo-service#25]
See screenshot. I think it would be better to have it stay on top. Otherwise, you can't find it at all or you press unsubscribe by mistake. 
![2015-07-24 18 12 11](https://cloud.githubusercontent.com/assets/6082553/8879136/bedf5dca-322f-11e5-8e5c-f5c98525b4f5.png)

**Comment by maxkueng** [comment]
When you have subscribed to 10 or more shows there is a second "Add more shows" button at the top. Should we lower that number?

**Comment by maxkueng** [comment]
Looks like this:
![ympc-subs](https://cloud.githubusercontent.com/assets/168709/8883264/c4d7e3a0-324d-11e5-951d-dca42fe6c51d.png)

**Comment by MathisB** [comment]
Awesome! 

On Fri, Jul 24, 2015 at 12:49 PM -0700, "Max Kueng" notifications@github.com wrote:

Looks like this:
